// angular-instantsearch/src/app/app.component.ts
import { Component } from '@angular/core';
import * as algoliasearch from 'algoliasearch';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  config = {
    indexName: 'instant_search',
    searchClient: algoliasearch('latency', '6be0576ff61c053d5f9a3225e2a90f76'),
  };
}

<header class="header">
  <h1 class="header-title">
    <a href="/">angular-instantsearch-app</a>
  </h1>
  <p class="header-subtitle">
    using
    <a href="https://github.com/algolia/angular-instantsearch">
      Angular InstantSearch
    </a>
  </p>
</header>

<div class="container">
  <ais-instantsearch [config]="config">
    <div class="search-panel">
      <div class="search-panel__filters">
        <ais-refinement-list attribute="brand"></ais-refinement-list>
      </div>

      <div class="search-panel__results">
        <div class="searchbox">
          <ais-search-box placeholder=""></ais-search-box>
        </div>

        <ais-hits>
          <ng-template let-hits="hits" let-results="results">
            <div *ngIf="hits.length === 0">
              No results found matching <strong></strong>.
            </div>

            <ol class="ais-Hits-list">
              <li class="ais-Hits-item" *ngFor="let hit of hits">
                <article>
                  <h1>
                    <ais-highlight attribute="name" [hit]="hit"></ais-highlight>
                  </h1>

                  <p>
                    <ais-highlight attribute="description" [hit]="hit"></ais-highlight>
                  </p>
                </article>
              </li>
            </ol>
          </ng-template>
        </ais-hits>

        <div class="pagination">
          <ais-pagination></ais-pagination>
        </div>
      </div>

    </div>
  </ais-instantsearch>
</div>

// react-instantsearch-hooks/src/App.tsx
import algoliasearch from 'algoliasearch/lite';
import {
  Highlight,
  Hits,
  InstantSearch,
  Pagination,
  RefinementList,
  SearchBox,
} from 'react-instantsearch-hooks-web';

import { Panel } from './Panel';

import type { Hit } from 'instantsearch.js';

import './App.css';

const searchClient = algoliasearch(
  'latency',
  '6be0576ff61c053d5f9a3225e2a90f76'
);

export function App() {
  return (
    <div>
      <header className="header">
        <h1 className="header-title">
          <a href="/">react-instantsearch-hooks-app</a>
        </h1>
        <p className="header-subtitle">
          using{' '}
          <a href="https://github.com/algolia/react-instantsearch">
            React InstantSearch Hooks
          </a>
        </p>
      </header>

      <div className="container">
        <InstantSearch searchClient={searchClient} indexName="instant_search">
          <div className="search-panel">
            <div className="search-panel__filters">
              <Panel header="brand">
                <RefinementList attribute="brand" />
              </Panel>
            </div>

            <div className="search-panel__results">
              <SearchBox placeholder="" className="searchbox" />
              <Hits hitComponent={Hit} />

              <div className="pagination">
                <Pagination />
              </div>
            </div>
          </div>
        </InstantSearch>
      </div>
    </div>
  );
}

type HitProps = {
  hit: Hit;
};

function Hit({ hit }: HitProps) {
  return (
    <article>
      <h1>
        <Highlight attribute="name" hit={hit} />
      </h1>
      <p>
        <Highlight attribute="description" hit={hit} />
      </p>
    </article>
  );
}
